version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: population_db
      POSTGRES_USER: popuser
      POSTGRES_PASSWORD: poppass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U popuser -d population_db"]
      interval: 2s
      timeout: 2s
      retries: 30
    volumes:
      - pgdata:/var/lib/postgresql/data

  get_data:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://popuser:poppass@db:5432/population_db
      SOURCE_URL: "https://en.wikipedia.org/w/index.php?title=List_of_countries_by_population_(United_Nations)&oldid=1215058959"
    command: ["python", "-u", "app/cli.py", "get_data"]
    restart: "no"

  print_data:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://popuser:poppass@db:5432/population_db
    command: ["python", "-u", "app/cli.py", "print_data"]
    restart: "no"

volumes:
  pgdata:
